name: task_master
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  path_provider: ^2.1.2
  flutter_svg: ^2.0.10+1
  package_info_plus: ^8.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # and

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/icons/

  fonts:
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat.ttf